version: '3.5'

services:
  postgres:
    container_name: postgres_container
    image: postgres
    env_file: .env
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-admin}
      POSTGRES_DB: ${DB_NAME:-todo-anysoft}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - '${DB_PORT:-5432}:5432'
    restart: unless-stopped
volumes:
  postgres:
